services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    ports:
      - "2345:5432"
    volumes:
      - ./src/main/resources/static/sql/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: vwdb
      POSTGRES_PASSWORD: change_me
      POSTGRES_DB: vwdb

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "15672:15672"
      - "5552:5552"
      - "5672:5672"
